import unittest
import sys

def factorial(n: int):
    if n < 0:
        raise ValueError("Факториал отрицательного числа не определен")
    if n == 0:
        return 1
    result = 1
    for i in range(1, n + 1):
        result *= i
        if result > sys.maxsize:
            raise ValueError(f"Факториал для {n} не поддерживается типом int")
    return result

class TestFactorial(unittest.TestCase):

    def test_minusnum(self):
        with self.assertRaises(ValueError):
            factorial(-5)
    
    def test_zero(self):
        self.assertEqual(factorial(0), 1)
    
    def test_littlenum(self):
        self.assertEqual(factorial(1), 1)
        self.assertEqual(factorial(5), 120)
        self.assertEqual(factorial(7), 5040)
    
    def test_bignum(self):
        self.assertEqual(factorial(10), 3628800)
        self.assertEqual(factorial(12), 479001600)
    
    def test_bigpronum(self):
        with self.assertRaises(ValueError):
            factorial(100)
    
    def test_neint(self):
        with self.assertRaises(TypeError):
            factorial(5.5)

if __name__ == '__main__':
    unittest.main()
